name: delete branch on PR merge
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          exclude: [master, staging, production]
          delete_closed_pr: true # delete a branch when PR is closed without merging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
