name: Deploy to dev

on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install
      
      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploying to dev
        run: echo "I wish I have a dev environment"
