name: Deploy to dev

on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install
      
      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploying to dev
        run: echo "I wish I have a dev environment"
      
      - name: display labels
        run: echo "${{ toJson(github.event.push.labels.*.name) }}"
      
      - name: Check for patch label
        if: contains(github.event.push.labels.*.name, 'patch')
        run: echo "patch label exists"
      
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          labels: '["patch"]'
      
      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"
